import {ArrowRight,BadgeCheck,CalendarDays,Check,Leaf,Phone,Quote,Shovel,Sparkles,Sprout,Star,Trees} from 'lucide-react';
import type {CSSProperties} from 'react';
import type {SiteViewModel} from '@/types/site';
import styles from './modern-service.module.css';

const icons=[Sprout,Shovel,Trees,Sparkles];

const Contact=({s}:{s:SiteViewModel})=><section id="contact" className="px-6 py-16" style={{background:s.theme.primary,color:'white'}}><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] opacity-70">Start a conversation</p><h2 className="mt-3 text-3xl font-semibold">{s.content.contactHeading}</h2><p className="mt-4 opacity-80">{s.content.contactDescription}</p><a className="mt-7 block text-xl font-semibold" href={`tel:${s.business.phone}`}>{s.business.phone}</a><a href={`mailto:${s.business.email}`} className="mt-2 block opacity-80">{s.business.email}</a></div><form action="/api/leads" method="post" className="grid gap-3 rounded-xl bg-white p-5 text-gray-900"><input type="hidden" name="siteId" value={s.id}/><input className="field" required name="name" aria-label="Name" placeholder="Your name"/><div className="grid grid-cols-2 gap-3"><input className="field" name="phone" aria-label="Phone" placeholder="Phone"/><input className="field" type="email" name="email" aria-label="Email" placeholder="Email"/></div><select name="service" className="field" aria-label="Service requested"><option>Choose a service</option>{s.services.map(x=><option key={x.id}>{x.name}</option>)}</select><textarea className="field min-h-24" required name="message" aria-label="Message" placeholder="How can we help?"/><button className="btn btn-primary" type="submit">Request a quote</button></form></div></section>;
const Shared=({s,dark=false}:{s:SiteViewModel;dark?:boolean})=><><section id="services" className={`px-6 py-20 ${dark?'bg-zinc-950 text-white':'bg-white'}`}><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold" style={{color:s.theme.accent}}>OUR SERVICES</p><h2 className="mt-3 text-3xl font-semibold md:text-4xl">{s.content.servicesHeading}</h2><p className="mt-3 opacity-65">{s.content.servicesDescription}</p><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{s.services.filter(x=>x.enabled).map((x,i)=><article key={x.id} className={`border p-6 ${dark?'border-zinc-700 bg-zinc-900':'border-gray-200 bg-gray-50'}`} style={{borderRadius:s.theme.radius}}><span className="text-xs font-bold opacity-40">0{i+1}</span><h3 className="mt-8 text-xl font-semibold">{x.name}</h3><p className="mt-3 text-sm leading-6 opacity-65">{x.shortDescription}</p></article>)}</div></div></section>{s.sections.about&&<section className="px-6 py-20"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-[.7fr_1.3fr]"><p className="text-sm font-bold uppercase tracking-widest" style={{color:s.theme.primary}}>About us</p><div><h2 className="text-3xl font-semibold">{s.content.aboutHeading}</h2><p className="mt-5 text-lg leading-8 opacity-70">{s.content.aboutDescription}</p><p className="mt-6 text-sm font-semibold">Serving {s.business.serviceArea}</p></div></div></section>}<Contact s={s}/></>;

export function ModernTemplate({site:s}:{site:SiteViewModel}){
 const services=s.services.filter(x=>x.enabled),hero=s.business.heroImage||'/images/evergreen-landscaping-hero.png',workImage='/images/evergreen-landscaping-wide.png';
 const review=s.testimonials[0]||{name:'A happy local homeowner',location:s.business.city,review:'The crew listened, offered smart ideas, and made the entire process easy. The finished yard looks better than we imagined.',rating:5};
 const vars={'--primary':s.theme.primary,'--accent':s.theme.accent,'--paper':s.theme.background,'--ink':s.theme.text,fontFamily:s.theme.font} as CSSProperties;
 return <main className={styles.site} style={vars}>
  <div className={styles.topbar}><span>Now scheduling free estimates</span><a href={`tel:${s.business.phone}`}><Phone size={13}/>{s.business.phone}</a></div>
  <nav className={styles.nav}><a className={styles.brand} href="#top"><span><Leaf size={22}/></span><b>{s.business.name}<small>{s.business.industry}</small></b></a><div className={styles.links}><a href="#services">Services</a><a href="#work">Our work</a><a href="#about">About</a><a href="#reviews">Reviews</a></div><a className={styles.navCta} href="#contact">Get a free quote <ArrowRight size={15}/></a></nav>
  <header id="top" className={styles.hero}><div className={styles.heroInner}><div className={styles.heroCopy}><p className={styles.eyebrow}><i/>{s.content.eyebrow}</p><h1>{s.content.headline}</h1><p className={styles.lede}>{s.content.heroDescription}</p><div className={styles.heroActions}><a className={styles.primaryButton} href="#contact">{s.content.primaryCta}<ArrowRight size={17}/></a><a className={styles.textButton} href="#services">{s.content.secondaryCta}<ArrowRight size={15}/></a></div><div className={styles.trust}><span><BadgeCheck/>Licensed & insured</span><span><Star/>5-star local service</span><span><CalendarDays/>Free estimates</span></div></div><div className={styles.heroVisual}><div className={styles.heroImage} style={{backgroundImage:`url("${hero}")`}} role="img" aria-label={`Beautiful landscaping by ${s.business.name}`}/><div className={styles.experience}><strong>12+</strong><span>years creating<br/>beautiful yards</span></div><div className={styles.leafBadge}><Leaf/></div></div></div></header>
  <section id="services" className={styles.services}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}><i/>What we do</p><h2>{s.content.servicesHeading}</h2></div><p>{s.content.servicesDescription}</p></div><div className={styles.serviceGrid}>{services.map((x,i)=>{const Icon=icons[i%icons.length];return <article key={x.id}><span className={styles.serviceNumber}>0{i+1}</span><Icon/><h3>{x.name}</h3><p>{x.shortDescription}</p><a href="#contact">Explore service <ArrowRight size={14}/></a></article>})}</div></section>
  {s.sections.gallery&&<section id="work" className={styles.work}><p className={styles.eyebrow}><i/>Our promise</p><div className={styles.workHeading}><h2>Outdoor spaces<br/><em>made memorable.</em></h2><p>Thoughtful plans, careful craftsmanship, and a clean finish on every property.</p></div><div className={styles.workGrid}><article className={styles.workPhoto} style={{backgroundImage:`linear-gradient(180deg,transparent 45%,rgba(10,31,23,.9)),url("${workImage}")`}}><div><small>DESIGN · PLANTING · CARE</small><h3>{s.business.city} backyard retreat</h3></div></article><article className={styles.promiseCard}><Leaf/><small>OUR STANDARD</small><h3>Beautiful work that lasts beyond the season.</h3><p>We respect your property, communicate clearly, and leave every space better than we found it.</p></article></div></section>}
  {s.sections.about&&<section id="about" className={styles.about}><div className={styles.aboutVisual} style={{backgroundImage:`url("${hero}")`}}><div><Leaf/><span><b>Quality grows here.</b><small>Thoughtful work. Lasting results.</small></span></div></div><div className={styles.aboutCopy}><p className={styles.eyebrow}><i/>Why choose us</p><h2>{s.content.aboutHeading}</h2><p>{s.content.aboutDescription}</p><p>{s.business.description}</p><ul><li><Check/>Friendly, experienced crews</li><li><Check/>Clear, upfront estimates</li><li><Check/>Respect for your home</li><li><Check/>Locally owned and operated</li></ul><a className={styles.outlineButton} href="#contact">Plan your project <ArrowRight size={16}/></a></div></section>}
  {s.sections.testimonials&&<section id="reviews" className={styles.reviews}><div><p className={styles.eyebrow}><i/>Neighbors say it best</p><h2>Good work gets<br/>people talking.</h2><p className={styles.stars}>{'★'.repeat(review.rating)} <span>Local homeowner review</span></p></div><article><Quote/><p>“{review.review}”</p><div><span>{review.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><b>{review.name}<small>{review.location||s.business.serviceArea}</small></b></div></article></section>}
  <section id="contact" className={styles.contact}><div><p className={styles.eyebrow}><i/>Let&apos;s get growing</p><h2>{s.content.contactHeading}</h2><p>{s.content.contactDescription}</p><a href={`tel:${s.business.phone}`}><Phone/><span><small>Prefer to call?</small><b>{s.business.phone}</b><em>{s.business.serviceArea}</em></span></a></div><form action="/api/leads" method="post"><input type="hidden" name="siteId" value={s.id}/><div><label>First name<input required name="name" placeholder="Jane"/></label><label>Phone<input name="phone" placeholder="(610) 555-0123"/></label></div><label>Email<input required type="email" name="email" placeholder="jane@email.com"/></label><label>What can we help with?<select name="service" defaultValue=""><option value="" disabled>Select a service</option>{services.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label>Tell us about your project<textarea required name="message" placeholder="What would you like to change or improve?"/></label><button type="submit">Request my free estimate <ArrowRight size={17}/></button><small>No pressure. No spam. Just helpful local advice.</small></form></section>
  <footer className={styles.footer}><div className={styles.brand}><span><Leaf size={22}/></span><b>{s.business.name}<small>{s.business.industry}</small></b></div><p>Beautiful outdoor spaces, thoughtfully created and carefully maintained.</p><div><b>{s.business.serviceArea}</b><a href={`tel:${s.business.phone}`}>{s.business.phone}</a><a href={`mailto:${s.business.email}`}>{s.business.email}</a></div></footer>
 </main>
}

export function BoldTemplate({site:s}:{site:SiteViewModel}){return <main className="bg-[#f4f0e8] text-zinc-950"><nav className="flex items-center justify-between border-b-2 border-black px-6 py-5"><b className="text-xl uppercase">{s.business.name}</b><a className="bg-[#f3b61f] px-5 py-3 font-black" href={`tel:${s.business.phone}`}>{s.business.phone}</a></nav><header className="px-6 py-20 md:py-28"><div className="mx-auto max-w-6xl"><p className="font-black uppercase tracking-[.25em]">{s.business.industry} • {s.business.city}, {s.business.state}</p><h1 className="mt-5 max-w-5xl text-6xl font-black uppercase leading-[.9] md:text-8xl">Work done right. <span className="text-[#c8472b]">No runaround.</span></h1><p className="mt-8 max-w-xl text-lg">{s.content.heroDescription}</p><a href="#contact" className="mt-9 inline-block bg-zinc-950 px-7 py-4 font-black uppercase text-white">Get a straight answer →</a></div></header><Shared s={s} dark/></main>}
export function CleanTemplate({site:s}:{site:SiteViewModel}){return <main className="bg-[#fbfaf7] text-[#25302d]" style={{fontFamily:'Georgia,serif'}}><nav className="mx-auto flex max-w-6xl justify-between px-6 py-8"><b className="text-xl">{s.business.name}</b><a href="#contact" className="border-b border-current pb-1 text-sm">Begin a conversation</a></nav><header className="px-6 py-24 text-center md:py-32"><p className="text-xs uppercase tracking-[.3em] text-[#8c7259]">{s.business.industry} in {s.business.city}</p><h1 className="mx-auto mt-7 max-w-4xl text-5xl font-normal leading-tight md:text-7xl">Clarity, care, and work that speaks for itself.</h1><p className="mx-auto mt-7 max-w-xl font-sans leading-7 opacity-60">{s.content.heroDescription}</p><a href="#contact" className="mt-9 inline-block bg-[#263934] px-7 py-3 font-sans text-sm text-white">{s.content.primaryCta}</a></header><Shared s={s}/></main>}
